version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'django_db'
      MYSQL_USER: 'niiya'
      MYSQL_PASSWORD: 'niiya'
      MYSQL_ROOT_PASSWORD: 'niiya'
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    #command: bash -c "sleep 10 && gunicorn --pythonpath /code myproject.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 300 --log-level debug"
    entrypoint: /code/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
      - ./logs:/code/logs
      - ./logrotate.conf:/code/logrotate.conf
    depends_on:
      - db

  nginx:
    image: nginx:1.19
    ports:
      - "8080:80"
      #- "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static
      - ./logs:/var/log/nginx
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  #nginx_logs: