# Generated by Django 3.2.9 on 2025-02-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetseaCatCsv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_id', models.IntegerField()),
                ('jan_cd', models.BigIntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'netsea_cat_csv',
            },
        ),
    ]
