# Generated by Django 3.2.9 on 2025-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetseaCatCsv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_id', models.IntegerField()),
                ('jan_cd', models.BigIntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('csv_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'netsea_cat_csv',
            },
        ),
        migrations.CreateModel(
            name='NetseaCatList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_id', models.IntegerField()),
                ('url', models.TextField(blank=True, null=True)),
                ('cat_name', models.TextField(blank=True, null=True)),
                ('cat_level', models.IntegerField(blank=True, null=True)),
                ('topics_path', models.TextField(blank=True, null=True)),
                ('cat_1', models.IntegerField(blank=True, null=True)),
                ('cat_2', models.IntegerField(blank=True, null=True)),
                ('cat_3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'netsea_cat_list',
            },
        ),
    ]
