# Generated by Django 3.2.9 on 2025-02-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsea_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetseaCatList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_id', models.IntegerField()),
                ('url', models.TextField(blank=True, null=True)),
                ('cat_name', models.TextField(blank=True, null=True)),
                ('cat_level', models.IntegerField(blank=True, null=True)),
                ('topics_path', models.TextField(blank=True, null=True)),
                ('cat_1', models.IntegerField(blank=True, null=True)),
                ('cat_2', models.IntegerField(blank=True, null=True)),
                ('cat_3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'netsea_cat_list',
            },
        ),
    ]
