# Generated by Django 3.2.9 on 2025-02-23 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netsea_data', '0002_netseacatlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netseacatcsv',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
